### PR TITLE
Wren fix

### LINKED ISSUE #35: CRM_report_new_referrals.py bug
Run level failure for NGHS101-X run caused by CRM_report_new_referrals.py for run 210813_M00766_0413_000000000-JM7C6 https://github.com/AWGL/SomaticAmplicon/blob/470105889f3ca065cec9933e297adca8e925db8d/1_SomaticAmplicon.sh#L638 The command crashed for some samples - error logs still within results. The command appeared to run for all samples, each time, even though the some hadn't finished. Possible that complete check on line 564 hadn't worked. 

Manually resolved the run by manually running the last lines of the script for each sample.

### PR DESCRIPTION
**Pull request by christianfiles**
## Change description

Made changes to create move_complete.txt as there was a bug where the pipeline would skip onto the next step before it was meant to.

## Related issues

closes #35 

## Justification for minor update

This small change does not affect the pipelines sensitivity

## Testing description

**Bioinformatics**

- Verify that new panel/ analysis sheets are applied correctly
- Verify that changes don't affect the triggering of the run level scripts

## Test data location

wren: `/data/output/results/210730_M00766_0410_000000000-JM7NV/`

## Bioinformatics checks

Manually checked that the worksheets generated by virtualhood were created for CRM (101X) and that the combinedQC.txt file was created for BRCA (102X).
The outputs can be seen in `/data/output/results/210730_M00766_0410_000000000-JM7NV/`

### CODE REVIEW

File: 1_SomaticAmplicon.sh [hunk 1]
```diff
@@ -524,6 +524,9 @@ fi
 if [ $custom_variants == true ]; then
     mkdir hotspot_variants
 
+    # Making marker file for 101X and Myeloid
```
Comment (erikwaskiewicz) [inline 1_SomaticAmplicon.sh]: Can you remove these comments please?

File: 1_SomaticAmplicon.sh [hunk 2]
```diff
@@ -552,14 +555,22 @@ if [ $custom_variants == true ]; then
         mv "$sampleId"_VariantReport.txt hotspot_variants/"$seqId"_"$sampleId"_"$target"_VariantReport.txt
 
     done
+
+# Making a marker file for 102X
```
Comment (erikwaskiewicz) [inline 1_SomaticAmplicon.sh]: can you remove these comments please?

**Review by erikwaskiewicz — CHANGES_REQUESTED** [review]
Hey,

Looks good, small change that only affects the triggering of the run level scripts - doesn't affect sensitivity of run.

Code all looks good, can you just remove the two commented out bits and we can merge

Cheers

**Review by erikwaskiewicz — APPROVED** [review]
All good, cheers
